# Generated by Django 5.2.4 on 2025-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otherstaff_remove_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('staff_in_charge', models.CharField(help_text='E.g., Hostel, Library, Sports, etc.', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='OtherStaff',
        ),
    ]
