# Generated by Django 5.2.4 on 2025-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_othersstaff_delete_otherstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff_in_charge',
            field=models.CharField(blank=True, help_text='For Others role: Hostel, Library, Sports, etc.', max_length=100, null=True),
        ),
    ]
