# Generated by Django 5.2.4 on 2025-09-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_othersstaff_user_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
