# Generated by Django 5.2.4 on 2025-09-14 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_semesterresult_delete_cgparecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGPARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('semester', models.PositiveIntegerField()),
                ('sgpa', models.FloatField()),
                ('total_credits', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['semester'],
                'unique_together': {('user', 'department', 'semester')},
            },
        ),
        migrations.DeleteModel(
            name='SemesterResult',
        ),
    ]
