# Generated by Django 5.2.4 on 2025-09-29 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cgparecord_delete_semesterresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6, message='Register number must be at least 6 characters.')]),
        ),
    ]
