# Generated by Django 5.2.4 on 2025-09-30 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_address_profile_dob_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgparecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='total_credits',
            field=models.IntegerField(),
        ),
    ]
