# Generated by Django 5.2.4 on 2025-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_cgparecord_created_at_alter_cgparecord_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seen_materials',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='accounts.studymaterial'),
        ),
    ]
