# Generated by Django 5.2.4 on 2025-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_student_seen_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtmessage',
            name='is_unsent',
            field=models.BooleanField(default=False),
        ),
    ]
